### ISSUE TITLE
Possible to make it work with addon 'ElitePlayerFrame'

### ISSUE THREAD

**Issue by kev41** [gashole/modui-UnitFramesImproved#3]
![elitemodui](https://cloud.githubusercontent.com/assets/21115526/24437746/2e935e4a-1443-11e7-9854-8e64593bbacb.jpg) 
I used to have ElitePlayerFrame addon work with ModUI like this. When using this mod it makes it not work. 

Here is the addon if you want to look on the code:
http://addons.us.to/addon/eliteplayerframe

Thanks alot of your work!

**Comment by gashole** [comment]
ElitePlayerFrame will not work because it replaces the PlayerFrame texture (which modui-TallHealthBar also replaces). 

*** 

Here is an AddOn to add modui's elite dragon texture to the player frame. It will work with or without modui-TallHealthBar.

To install, copy/paste the code below into new text files and save them as modui-ElitePlayerFrame.toc and core.lua. Once done, move them to a new folder called modui-ElitePlayerFrame in your AddOns folder.

modui-ElitePlayerFrame.toc
```
## Interface: 11200
## Title: modui-ElitePlayerFrame
## Notes: Adds modui's elite dragon texture to the player frame.
## RequiredDeps: modui
core.lua
```
core.lua
```


    PlayerFrame.Elite = PlayerFrameTexture:GetParent():CreateTexture(nil, 'BORDER')
    PlayerFrame.Elite:SetWidth(128) PlayerFrame.Elite:SetHeight(128)
    PlayerFrame.Elite:SetPoint('TOPLEFT', PlayerFrame)
    PlayerFrame.Elite:SetTexture[[Interface\AddOns\modui\unitframe\UI-TargetingFrame-Elite]]
    PlayerFrame.Elite:SetTexCoord(1, 0, 0, 1)

    --

```
